### ISSUE TITLE
zeep dependency is hardly optional …

### ISSUE THREAD

**Issue by mcepl** [AnalogJ/lexicon#294] opened 2018-09-25 12:08 UTC
When https://github.com/AnalogJ/lexicon/blob/1e025e41c21298f795ce81d58573bfd911db382b/lexicon/providers/subreg.py#L29 unconditionally uses it.

**Comment by adferrand** [comment] 2018-09-25 14:40
It is effectively really optional. The idea here it that if you do not need to use the subreg provider, then you do not have to install its dependencies. In this case, yes, you cannot instantiate the provider, but it does not matter, because you will not try to do something like `lexicon subreg create ...`

However, you still need to always protect the import statements on optional packages from an ImportError. Because the Lexicon client, at high level, will import each provider module (see https://github.com/AnalogJ/lexicon/blob/1e025e41c21298f795ce81d58573bfd911db382b/lexicon/__main__.py#L59)

It does that to know what provider is available, and for each one, what are the specific options available from the command line (by instantiating the SubArgParser, not the Provider itself). And of course, importing a module requires that all import directives do not raise an exception.

It is right that this behavior is not easy to see through the source code. At least a unit test should ensure that all optional imports are correctly handled through a vanilla installation of lexicon with only the required imports. Told to @AnalogJ about that here: #293

**Comment by AnalogJ** [comment] 2018-09-25 15:14
@adferrand summarized it quite nicely.

Lexicon tries to support as many providers as possible, but as a user you shouldn't need to install the dependencies of 50 providers if you only need to run 3. The way that we solve this issue is by requiring  that non-standard dependencies are added to the [setup.py](https://github.com/AnalogJ/lexicon/blob/master/setup.py#L89-L97) file as `extras_require` groups.

This allows end users to install lexicon and just the specific providers they need. 
```
pip install dns-lexicon
pip install dns-lexicon[subreg]
pip install dns-lexicon[namecheap]
pip install dns-lexicon[cloudflare] # if an extras_require group is not defined, pip just exits without an error.
```

I hope that all makes sense. I'm going to close this issue for now, but feel free to keep this discussion going.

**Closed by AnalogJ** 2018-09-25 15:14 UTC

**Comment by mcepl** [comment] 2018-09-25 17:35
> I hope that all makes sense.

Well, not completely. Couldn't we get an option to run at least part of the test suite without all packages installed. I am a packager for openSUSE, and packaging of all those packages required for running test suite (particularly ``zeep`` and all its very many dependencies) is really obnoxious. So, I have now choice between packaging all those packages, which I wouldn't need otherwise, and not running test suite completely (or patching out particular many tests).

**Comment by AnalogJ** [comment] 2018-09-25 18:07
hm, are you saying you'd like to run the test suite for just an individual provider?

CONTRIBUTING.md kind of touches on how to do it. Something like this should work (havent tested it though)

```
pip install -r requirements.txt
pip install -r test-requirements.txt
pip install .[$PROVIDER_NAME]

py.test tests/providers/test_${PROVIDER_NAME}.py
```
I hope I'm not mis-understanding your request

**Comment by hank** [comment] 2018-09-25 20:45
As someone who just wrote a provider, I can confirm the above method of running test for an individual provider works perfectly.
