### ISSUE TITLE
DnsMadeEasy authentication issue

### ISSUE THREAD

**Issue by pavinjosdev** [AnalogJ/lexicon#152] opened 2017-11-26 21:33 UTC
Hey everyone,

Dnsmadeeasy is throwing an exception with the following command:
`lexicon dnsmadeeasy --auth-username="xxxx" --auth-token="xxxx" list mydomain.com TXT` where `auth-username` is API key & `auth-token` is Secret key.

~~~
root@test:~# lexicon dnsmadeeasy --auth-username="xxxx" --auth-token="xxxx" list mydomain.com TXT
Arguments: Namespace(action='list', auth_token='xxxx', auth_username='xxxx', content=None, delegated=None, domain='mydomain.com', identifier=None, name=None, priority=None, provider_name='dnsmadeeasy', ttl=None, type='TXT')
Starting new HTTPS connection (1): api.dnsmadeeasy.com
https://api.dnsmadeeasy.com:443 "GET /V2.0/dns/managed/name?domainname=mydomain.com HTTP/1.1" 403 79
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    load_entry_point('dns-lexicon==2.1.12', 'console_scripts', 'lexicon')()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/__main__.py", line 69, in main
    client.execute()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 38, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/dnsmadeeasy.py", line 40, in authenticate
    raise e
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.dnsmadeeasy.com/V2.0/dns/managed/name?domainname=mydomain.com
~~~

I've already made sure the keys are correct. Appreciate any tips on troubleshooting this.

Kind regards,
Pavin Joseph.

**Comment by AnalogJ** [comment] 2017-11-27 17:37
Hey Pavin,

Unfortunately I don't have a personal DNSMadeEasy account, so its a bit hard to test it myself. However it does look like we're using v2.0 of the API, which is the latest one mentioned on the website, and the provider does have working recordings, which means it did work some someone in the past. 

If I had to guess, this sounds like an parameter/documentation error. 

You you sure you are using the correct auth values?
`--auth-username="API-KEY"` `--auth-token="API-SECRET"`

**Comment by pavinjosdev** [comment] 2017-11-28 10:21
Hi,

> You you sure you are using the correct auth values?

Yes, I've checked these values using the official Dnsmadeeasy perl scripts and was able to authenticate.

> Unfortunately I don't have a personal DNSMadeEasy account, so its a bit hard to test it myself.

I'm using v2.0 API. There is a sandbox environment for testing it [here](http://api.sandbox.dnsmadeeasy.com/V2.0/account/new).

**Comment by nydr** [comment] 2017-11-28 12:06
I've opened a PR which should resolve this. I suspect it's caused by Babel depending on the `en_US` locale being installed on your machine so I replaced that part with the python standard library

**Comment by pavinjosdev** [comment] 2017-11-28 19:30
Its working now. Thanks for the fix.

**Comment by rorpage** [comment] 2017-12-01 19:01
@pavinjosdev Did you clone this repo and branch and build/run it locally?

**Comment by AnalogJ** [comment] 2017-12-01 19:24
v2.1.13 is now released and includes a fix for this issue.

**Closed by AnalogJ** 2017-12-01 19:24 UTC
