### ISSUE TITLE
List all domains?

### ISSUE THREAD

**Issue by techtonik** [AnalogJ/lexicon#59] opened 2016-10-08 22:46 UTC
How to make `domain` argument optional? For example, DreamHost API list query contains all domains configured for certain account. Also, what is the 'domain' lexicon? Is it `zone` or `record`?

```
[{u'account_id': u'102',
  u'comment': u'',
  u'editable': u'0',
  u'record': u'argo.net',
  u'type': u'A',
  u'value': u'192.168.1.1',
  u'zone': argo.net'},
 {u'account_id': u'102',
  u'comment': u'',
  u'editable': u'0',
  u'record': u'argomail.net',
  u'type': u'MX',
  u'value': u'0 aspmx.l.google.com.',
  u'zone': u'argomail.net'},
...
```

**Comment by AnalogJ** [comment] 2016-10-10 05:48
Hey @techtonik 

Yeah I noticed that the DreamHost list API doesn't take a domain parameter. I wouldn't ignore the domain parameter (as that's a pretty standard parameter used internally) Instead I would just use the domain parameter to filter the output of the list API, and ensure that the domain exists in the list. Its basically what we do in [LuaDNS](https://github.com/AnalogJ/lexicon/blob/master/lexicon/providers/luadns.py#L16-L25)

In this case it looks like `zone` == `domain`

**Comment by techtonik** [comment] 2016-10-10 07:47
Yes, I've got this `zone == domain` convention too. But have you considered the possibility for the library to list all the managed zones given the authkey an provider?

**Comment by AnalogJ** [comment] 2016-10-10 15:23
Hey @techtonik 
Though listing all zones could be interesting, I'm not sure it would be very useful as Lexicon doesn't let you manage zones, only records. 

Yeah `zone` is the technically correct term: `my.example.com`, `test.example.com`, `hello.example.com` are all different zones, while `example.com` is the domain. However its pretty common to see `domain` used interchangeably with `zone`, especially since most users aren't familiar with DNS terminology. 

I'm probably going to keep calling it `domain`, but maybe I could add a `zone` alias if you think it'll help.

**Comment by techtonik** [comment] 2016-10-10 21:04
Actually I thought that `example.com` is the zone and `my.example.com` is a configured domain. Google DNS docs, for example use `zone` to refer to DNS object, and use `domain` when they refer to specific records. https://cloud.google.com/dns/quickstart

**Comment by srvrco** [comment] 2016-11-17 08:46
From my viewpoint listing all domains is essential. 

trying to add a DNS challenge for Let's Encrypt certificates you need to add a text DNS record for the relevant FQDN  (e.g.  ._acme-challenge.sub1.sub2.example.com. ), but you don't know if this needs to be added to example.com or sub2.example.com as the "domain" entity.   Hence a list of all domains would enable you to determine which is the entity it should be added to.

**Comment by AnalogJ** [comment] 2016-11-17 09:22
@srvrco I'm not sure exactly what you're asking for. If you want all the records for `example.com` that should be as easy as:

```
lexicon cloudflare list example.com CNAME
```

It should return all CNAME records for `example.com`, including its subdomains: `sub1.example.com`,  `sub2.sub1.example.com`, `www.example.com`, etc

@techtonik 's question was regarding multiple domains in the same DNS provider, ie. `example.com`, `test.com`, `example.net`

**Comment by AnalogJ** [comment] 2016-11-17 09:26
@techtonik I'm going to close this issue as I'm not sure it would be useful to list domains managed by a provider as Lexicon doesn't let you manage domains, only records.

**Closed by AnalogJ** 2016-11-17 09:26 UTC

**Comment by srvrco** [comment] 2016-11-17 09:55
I'm not sure if you want a response or not since you closed this ...... 

My request was to list all domains, since otherwise it's tricky to get to the records.   

If I know that I want to add the record "_acme-challenge.sub1.sub2.example.com" ... but I don't actually own example.com ... only sub2.example.com  how do I find that out ?   other than just try example.com, and get an error, so then try sub2.example.com ?

**Comment by AnalogJ** [comment] 2016-11-17 16:29
@srvrco 

That's where I'm confused though. sub1.sub2.example.com is just a record in example.com, atleast for 99% of the providers I've dealt with. I sorry if I'm missing something, I can't think of a use case where a developer will have permissions to add DNS records to `*.sub1.example.com` but not to `*.example.com`. Most services that I know of that assign sub-domains don't give DSN record access. 
This might just be one of my incorrect assumptions. 

As of right now, if you send `lexicon` a request for listing records on a subdomain, it strips the subdomain component and just lists all records on the domain anyways: https://github.com/AnalogJ/lexicon/blob/master/lexicon/client.py#L10-L12

    lexicon cloudflare list example.com CNAME

Is the exact same as

    lexicon cloudflare list sub1.sub2.example.com CNAME

If you have a usecase for a provider which lets you manage subdomains seperate from the actual domain, I'm more than willing to tweak `lexicon` to support it.

**Comment by srvrco** [comment] 2016-11-18 08:44
What if I ask the question differently ( since sub1.example.com and example.com are both FQDN).   How do you define a domain name ? 

Example.com is a domain name on your definition (if I understand correctly ) and sub1.example.com is a record / subdomain within that domain. 

what about example.co.uk ? is the domain "co.uk" ?  and example.co.uk a record within it ?

**Comment by AnalogJ** [comment] 2016-11-18 23:19
@srvrco 
Seems like we're conflating a few different issues here.
`Lexicon` doesn't care about domains, your DNS provider's API does.  If you use `digitalocean`, you can have multiple `domains/zones` registered with it, and the API endpoint that `lexicon` calls to retrieve the record expects a `DOMAIN_NAME`, eg. `example.com` (not `sub1.example.com`)
Most of the DNS providers that we support work in the same way (though some require a request to retrieve a domain specific identifier first, eg. `cloudflare`). 

The library that we use to extract the domain/zone from `sub1.sub2.example.com` (or whatever domain you give us) correctly handles TLD's. So if you have `example.co.uk` registered with `cloudflare`, `lexicon`is able to correctly retrieve the records for that zone. 

As I said before, I'm not exactly sure what use-case you're trying to solve. I'd love a bit more information. Does `lexicon cloudflare list sub1.sub2.example.com CNAME` give you the data you need?

**Comment by quinncomendant** [comment] 2019-02-11 17:35
I just came across this old thread. I have a use case similar to @srvrco, and I think I can explain what is required:

`example.com` and `sub1.example.com` can be seperate zones, with non-overlapping administrative access. As @srvrco mentioned, `sub1.example.com` is a FQDN, and can have its own name servers and DNS service provided separately from `example.com`. In this case, I may have access to manage records in the zone of `sub1.example.com`, but not `example.com`. This is not uncommon at large institutions, who want to grant DNS administration of a subdomain to a specific department, while restricting access to the second-level zone. 

To continue the example, I would manage my zone by accessing the name of the _zone_, like this:

    lexicon cloudflare list sub1.example.com CNAME

But if lexicon “strips the subdomain component and just lists all records on the domain”, as @AnalogJ suggests, then this query will result in an error (e.g., because I don't manage `example.com` on my account at cloudflare). 

It can lead to some confusion when not using correct terms. I would be in favor of renaming "domain" to "zone", because:

- `example.com` is a domain
- `sub1.example.com` is a subdomain
- `example.com` is a zone
- `sub1.example.com` might be a zone – or maybe not!

While lexicon accepts a _domain_, what it really should act on is a _zone_. :)

As for the need to list all zones in an account at a DNS provider, this is a pretty useful feature when managing thousands of zones and need to audit the configuration or loop through domains to modify dns records in each zone, e.g.:

```shell
for P in $PROVIDERS; do
    for Z in $(lexicon $P list-all-zones); do
        lexicon $P update $Z TXT 'v=spf1 a -all';
    done
done
```

**Comment by AnalogJ** [comment] 2019-02-11 17:52
Hey @quinncomendant I think this issue has been solved with the addition of the `--delegated` flag.

Can you confirm that the following command works as intended?

```
lexicon --delegated sub1 cloudflare list sub1.example.com CNAME 
```
