### ISSUE TITLE
ENV vars are not used for testing

### ISSUE THREAD

**Issue by kaz** [AnalogJ/lexicon#326] opened 2018-12-04 19:19 UTC
Since v3.0.0,
I found that ConfigResolver is reading invalid environment vars (such as `LEXICON_NONE_TOKEN`) in a test for any providers.
Provider-specific environment vars (such as `LEXICON_CONOHA_TOKEN`) have been not referred.

I think it is because `config.resolve('lexicon:provider_name')` returns *None* on a test process.

Is this intended behavior?

**Comment by adferrand** [comment] 2018-12-04 20:03
No, it is not the intended behavior... I forgot to add the provider name in the test config. PR is coming.

**Comment by AnalogJ** [comment] 2018-12-05 02:10
Closing this since #327 is merged with @adferrand 's fix.

**Closed by AnalogJ** 2018-12-05 02:10 UTC
